---
waning_gib: https://teachers.henrico.k12.va.us/staffdev/clough_d/moon/Photos_files/Media/Waninggibbous/Waninggibbous.jpg
waxing_cresc: https://teachers.henrico.k12.va.us/staffdev/clough_d/moon/Photos_files/Media/waxingcrescent/waxingcrescent.jpg
full: https://teachers.henrico.k12.va.us/staffdev/clough_d/moon/Photos_files/Media/fullmoon/fullmoon.jpg
third_quart: https://images.fineartamerica.com/images-medium-large-5/third-quarter-moon-nasagsfc-svsscience-photo-library.jpg
first_quart: https://teachers.henrico.k12.va.us/staffdev/clough_d/moon/Photos_files/Media/firstquarter/firstquarter.jpg
waning_cresc: https://teachers.henrico.k12.va.us/staffdev/clough_d/moon/Photos_files/Media/waningcrescent/waningcrescent.jpg
last_quart: https://teachers.henrico.k12.va.us/staffdev/clough_d/moon/Photos_files/Media/lastquarter/lastquarter.jpg
waxing_gib: https://teachers.henrico.k12.va.us/staffdev/clough_d/moon/Photos_files/Media/waxinggibbous/waxinggibbous.jpg
new: https://upload.wikimedia.org/wikipedia/commons/d/dd/New_Moon.jpg
extra: 'kne'
